### ISSUE TITLE
Cannot delete translation when using key_value backend.

### ISSUE THREAD

**Issue by dimir** [ruby-i18n/i18n#172]
``` shell
$ rails console
Loading development environment (Rails 3.2.8)
```

let's get a reference to our db

``` ruby
irb(main):016:0> translations = Redis.new(:db => 'foo')
=> #<Redis client v3.0.2 for redis://127.0.0.1:6379/0>
```

let's add an entry 'en.items' => 'the items' 

``` ruby
irb(main):017:0> I18n.backend.store_translations(:en, {:items => 'the items'})
=> {:items=>"the items"}
```

see if that worked

``` ruby
irb(main):018:0> translations['en.items']
=> "[\"the items\"]"
```

that worked, now let's try to delete 'en.items'

``` ruby
irb(main):019:0> I18n.backend.store_translations(:en, {:items => nil})
=> {:items=>nil}
```

see if that worked

``` ruby
irb(main):020:0> translations['en.items']
=> "[null]"
```

nope, the entry is still there and now translates to "null"

**Comment by sshaw** [comment]
> The idea of KeyValue backend to have basic interface working for most KeyValue stores. Implementing key removing would be tricky as different stores have different methods for it 

Agreed. But the problem is an important implementation detail is hidden: the way the key is created.

This is sorta exposed by `flatten_translations`, but that method is not ideal. 

There should be a `key` method on `I18n::Backend::Base` to make `store.delete` less error prone.
