### ISSUE TITLE
I18n.locale cached in rspec

### ISSUE THREAD

**Issue by tompave** [ruby-i18n/i18n#256]
When testing some localization logic of my controllers, with Rspec, the value of `I18n.locale` gets _cached_.

I can see it change for each simulated request, in `spec/controllers/`, but then it will remain stuck with whatever value was returned when testing the very last request.  

For example, this test passes, but it will change the value of `I18n.locale` for all the remainder of the test suite:

``` ruby
it "should change the locale" do
  get :index, { param_that_will_be_used_by_controller: 'fr' }
  expect(I18n.locale).to eq :fr
  expect(response.status).to eq(200)
end
```

At the moment I've solved the problem by manually setting it to nil:

``` ruby
after(:all) { I18n.locale = nil }
```

...but I was wondering if there is a more direct way to solve the problem.

**Comment by jmuheim** [comment]
Is this somewhere in the docs? I always wondered why seemingly randomly some specs failed because of the wrong language strings that was tested on.

**Comment by jmuheim** [comment]
Your workaround didn't work for me. I have created a new question on StackOverflow:

[Rails: random failures in specs because of wrong default locale](http://stackoverflow.com/questions/36040661/rails-random-failures-in-specs-because-of-wrong-default-locale)
