### ISSUE TITLE
can not load translations from (already deleted file)

### ISSUE THREAD

**Issue by rngadam** [ruby-i18n/i18n#301]
i18n 0.6.11

after creating and then deleting a translation file config/locales/health/en.yml, I get the following error:

```
$ RAILS_ENV=development rails console
~/.rvm/gems/ruby-2.1.2/gems/i18n-0.6.11/lib/i18n/backend/base.rb:185:in `rescue in load_yml': can not load translations from webapp/config/locales/health/en.yml: #<Errno::ENOENT: No such file or directory @ rb_sysopen - webapp/config/locales/health/en.yml> (I18n::InvalidLocaleData)
```

The directory is indeed not there anymore, so why is it trying to load it?

test works:

```
RAILS_ENV=test rails console
Loading test environment (Rails 4.1.1)
[1] pry(main)>
```

...tried stopping guard, `rake tmp:clear` with no effect.

Then cloned the repository and running from there worked. Went back to the old repository and it also started working. 

interactions with spring maybe?

```
$ spring status
Spring is running:

91085 spring server | webapp | started 69 hours ago          
 6277 spring app    | webapp | started 1 min ago | development mode    
 6278 spring app    | webapp | started 1 min ago | test mode    
 6279 spring app    | webapp | started 1 min ago | staging mode
```

**Comment by edgartheunready** [comment]
I'm having this problem. What caches do I need to delete?

**Comment by edgartheunready** [comment]
Found the answer: http://stackoverflow.com/questions/25300598/rails-if-validation-fail-shows-error-i18ninvalidlocaledata-can-not-load-t
