### ISSUE TITLE
I18n.reload! should clear the Cache backend

### ISSUE THREAD

**Issue by lawrencepit** [ruby-i18n/i18n#36]
Currently I18n.reload! does not clear the Cache backend.

Patch is at:

http://github.com/lawrencepit/i18n/tree/cache_reload

Note: it relies on the caching store automatically flushing least recent cache hits, which is the case for memorystore, memcached, etc. We don't want to do I18n.cache_store.clear, as that would clear out the entire cache including non-i18n items, which would be too much.

**Comment by dmitry** [comment]
What about https://github.com/svenfuchs/i18n/pull/70 ?

**Comment by sandstrom** [comment]
Is `I18n.reload!` used outside development?

If not the solution should be a bit easier. Perhaps just setting a timestamp as i18n cache namespace would suffice (https://github.com/svenfuchs/i18n/blob/master/lib/i18n/backend/cache.rb#L59)?

**Comment by pfeifferj** [comment]
Is there any workaround for this yet? My translations aren't updating in prod. I have tried clearing the cache multiple times.

**Comment by radar** [comment]
@pfeifferj Please open a new issue that provides clear steps to reproduce the issue that you're seeing.
