### ISSUE TITLE
Regression with leading zero keys

### ISSUE THREAD

**Issue by aleksejleonov** [ruby-i18n/i18n#456]
## What I tried to do

With next localization keys:

```yml
en:
  test_data:
    '000': 'Value 000'
    '001': 'Value 001'
    '002': 'Value 002'
    '111': 'Value 111'
```

`I18n` version `1.1.1` it works fine:
```ruby
> I18n.t('test_data.001')
=> "Value 001"
```

`I18n` version `1.4.0` didn't work:
```ruby
> I18n.t('test_data.001')
=> "translation missing: en.test_data.1"
```

## What I expected to happen

Behavior should be consistent with version `1.1.1`.

## What actually happened

Behavior changed.

## Versions of i18n, rails, and anything else you think is necessary

Changes was introduced in https://github.com/ruby-i18n/i18n/commit/38732a6dba26754a9bba8279ef2709290628e511

https://github.com/ruby-i18n/i18n/blob/38732a6dba26754a9bba8279ef2709290628e511/lib/i18n.rb#L368

----

I believe, i18n should't try convert keys to number if key starts with `0`.

So, regexp:
https://github.com/ruby-i18n/i18n/blob/38732a6dba26754a9bba8279ef2709290628e511/lib/i18n.rb#L367
should be changed with: `\A[-+]?[1-9]\d*\z`.

This way strings like `12345` would be converted to numbers, but strings like `0001` stay untouched.

**Comment by radar** [comment]
Thanks for letting us know about it. It seems like you know the solution already. Please submit a PR to fix it.

**Comment by aleksejleonov** [comment]
@radar
Done in #457.
