### ISSUE TITLE
Investigate JRuby test failures

### ISSUE THREAD

**Issue by radar** [ruby-i18n/i18n#459]
JRuby is failing some of the Travis tests, but only seemingly with the default Gemfile + the Rails master gemfile: https://travis-ci.org/ruby-i18n/i18n/builds/476071556?utm_source=github_status&utm_medium=notification.

I cannot reproduce this issue locally. I would love some help to investigate this issue.

**Comment by knapo** [comment]
Hey @radar!

I did a quick check and found out that under a certain jruby builds (even not versions) `hash` or `Hash` is weirdly calculated - it has the same value for different Hashes.

```
puts "I18n.cache_key_digest #{key.class} #{key.inspect} #{key.hash}"
I18n.cache_key_digest  Hash {:foo=>1, :bar=>2} -2017438026604914721
I18n.cache_key_digest  Hash {:foo=>2, :bar=>1} -2017438026604914721
```

I think it's safe to always calculate `hash` from string, and I believe it was the initial idea behind this.

Also, there were a random failures, which (I think) were related to the fact that the cache was not cleared after each test case. 

I'll submit a PR in a while.

**Comment by radar** [comment]
Thank you very much for looking into this @knapo!
