### ISSUE TITLE
There is no way to uppercase abbreviated month name using localize method

### ISSUE THREAD

**Issue by blaszczakphoto** [ruby-i18n/i18n#463]
## What I tried to do

I wanted to have formatted and localized date with month name uppercased and abbreviated.
```ruby
# without uppercase works good
I18n.localize(Time.zone.local(2018, 5, 11), format: "%e %b %Y", locale: :de)
=> "11 Mai 2018"

# but with uppercase..
# formatting from https://apidock.com/ruby/DateTime/strftime
I18n.localize(Time.zone.local(2018, 5, 11), format: "%e %^b %Y", locale: :de)
=> "11 MAY 2018"
```

## What actually happened

The `%^b`directive is no supported in I18n and it returns always english version of the string.

## What I expected to happen

When `%^b`directive is used, the I18n maps use upcase method in abbreviated month name.

## Versions of i18n, rails, and anything else you think is necessary
```
rails (5.2.2)
i18n (1.5.2)
```

## The code where upcasing might take place:
https://github.com/ruby-i18n/i18n/blob/master/lib/i18n/backend/base.rb#L250-L261

**Comment by radar** [comment]
A patch to fix this would be very welcome!
