### ISSUE TITLE
Update or remove link from github repo page

### ISSUE THREAD

**Issue by shioyama** [ruby-i18n/i18n#466]
The link that features prominently at the top of ruby-i18n/i18n points to https://rails-i18n.org/wiki, which is a broken link (not to mention this is a *ruby* gem, so a "rails i18n" website doesn't really seem appropriate).

![screenshot-2019-02-03-17-47-01](https://user-images.githubusercontent.com/561827/52174800-ac637b80-27dc-11e9-89ab-eeaed149ed99.png)

It's great to see some action creating an organization for i18n, but if this website link is not either removed or fixed the project will still look kind of dead/outdated.

**Comment by radar** [comment]
I have just removed this link.
