### ISSUE TITLE
MissingInterpolationArgument doesn't throw if there was no context at all passed

### ISSUE THREAD

**Issue by brendo** [ruby-i18n/i18n#474]
## What I tried to do

I added this test in `test/backends/exceptions_test.rb` (apologies if this is the wrong place):

```ruby
test "throw message: MissingInterpolationArgument message from #translate" do
  begin
    store_translations('en', :foo => "%{bar}")
    I18n.t(:foo, :locale => :en, :throw => true)
  rescue I18n::MissingInterpolationArgument => exception.message
  end
  assert_equal 'missing interpolation argument "bar" in "%{bar}" ({} given)', exception.message
end
```

## What I expected to happen

I'd expect this to throw the `MissingInterpolationArgument` error and the test pass.

## What actually happened

I receive the following message instead:

```
  1) Error:
I18nBackendExceptionsTest#test_throw_message:_MissingInterpolationArgument_message_from_#translate:
NameError: undefined local variable or method `exception' for #<I18nBackendExceptionsTest:0x00007fe83d951b68>
Did you mean?  exception_details
```

## Versions of i18n, rails, and anything else you think is necessary

`master` of this gem 👍 

----

A slightly modified test shows that this behaviour works when _some_ keyword arguments are passed (below passes `:baz` => 'hi'):

```ruby
test "throw message: MissingInterpolationArgument message from #translate" do
  begin
    store_translations('en', :foo => "%{bar}")
    I18n.t(:foo, :baz => 'hi', :locale => :en, :throw => true)
  rescue I18n::MissingInterpolationArgument => exception
  end
  assert_equal 'missing interpolation argument :bar in "%{bar}" ({:baz=>"hi"} given)', exception.message
end
```

I believe this is because [interpolation logic only runs when the `options` hash isn't empty](https://github.com/ruby-i18n/i18n/blob/master/lib/i18n/backend/base.rb#L56-L63).

**Comment by radar** [comment]
```

**Comment by brendo** [comment]
Apologies for the typo, but the error is still not what should happen.

```
  1) Error:
I18nBackendExceptionsTest#test_throw_message:_MissingInterpolationArgument_message_from_#translate:
NoMethodError: undefined method `message' for nil:NilClass
```

This is because no Exception was raised, when I would expect one to be because the translation string wanted `bar` to exist, but there was no `bar` available.

Are you able to clarify the expectations of i18n here? If no context is provided, is the interpolation logic meant to be skipped (and therefore act in current state, no exception raised), or should the logic always work, and an exception be raised?

**Comment by radar** [comment]
Your code has `assert_equal` outside of the `rescue` block, which means that the `exception` variable will not be available there. Moving `assert_equal` into the block (above the `end`) will probably make your code work.

**Comment by brendo** [comment]
> Your code has `assert_equal` outside of the `rescue` block, which means that the `exception` variable will not be available there. Moving `assert_equal` into the block (above the `end`) will probably make your code work.

Sorry, I was just following the example that already exists in [`backend/exceptions_test.rb`](https://github.com/ruby-i18n/i18n/blob/master/test/backend/exceptions_test.rb#L16-L30):

https://github.com/ruby-i18n/i18n/blob/ba83938beb6f9a042ac450c9fd3253de0c9fb6b1/test/backend/exceptions_test.rb#L16-L30

Rather than going back and forth on syntax, can you confirm the expected behaviour?

If no context is provided, is the interpolation logic meant to be skipped (and therefore act in current state, no exception raised), or should the logic always work, and an `MissingInterpolationArgument` be raised?
