### ISSUE TITLE
I18n::Backend::Base#translate_localization_format stagnge behaviour

### ISSUE THREAD

**Issue by alaexeyshustov** [ruby-i18n/i18n#479]
I have array of localized month abbriviations 
%w(Jan. Feb. März Apr. Mai Juni Juli Aug. Sept. Okt. Nov. Dez.)
When I18n.localize method is called with formats like %a %A %b %B, the return value is unexpected. 

I expect that return value for 1st month will be Jan.

But it returns Feb.
The translate_localization_format method tries to get value from array by index, and i need to have fake value on first place in the array.

I18n v1.0.0

date.abbr_month_names.de = %w(Jan. Feb. März Apr. Mai Juni Juli Aug. Sept. Okt. Nov. Dez.)
date = Date.parse('2019-01-01')
I18n.l(date, locale: 'de', format: '%b') # outputs Feb.

**Comment by radar** [comment]
You're right that you need to have a fake value on the first place in the array. This is what the `rails-i18n` gem does too:

https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/de.yml#L20-L33
