### ISSUE TITLE
An i18n file with the extension ".file" results in an infinite loop

### ISSUE THREAD

**Issue by grimnebulin** [ruby-i18n/i18n#484]
## What I tried to do

I created a translations file in my Rails project with the extension ".file" and added it to I18n.load_path.

## What I expected to happen

An unknown file type error.

## What actually happened

Server fails to start up successfully.  I believe this is because the load_file method in lib/i18n/backend/base.rb will call any "load_$extension" method that exists, and so an extension of "file" causes that method to call itself recursively until the stack blows up.

## Versions of i18n, rails, and anything else you think is necessary

I'm on Rails 4.2.11.  I don't see a separate i18n gem in any of my Gemfiles.  In any case, the unlimited recursion I see is currently on the master branch of i18n.

Note also that the comment above the load_file method states that it delegates to load_rb or load_yml, but it also apparently supports JSON files, since there's a load_json method.

**Comment by radar** [comment]
I think the simplest solution here is... to not do that.

I can't think of how people using this library _as it is documented_ would encounter this bug. You would have to actively seek it out.

As this is an issue _without_ a PR and it's not _critical_ to fix it, I'm going to close it.

Thanks for reporting it anyway!
