### ISSUE TITLE
Default with symbol interpolates twice.

### ISSUE THREAD

**Issue by sliiser** [ruby-i18n/i18n#494]
## What I tried to do

```
I18n.backend.store_translations('en', a: '%{key}')
I18n.t('missing', default: :a, key: '%{b}')
```

## What I expected to happen

`"%{b}"`

## What actually happened

`I18n::MissingInterpolationArgument: missing interpolation argument :b in "%{b}" ({:key=>"%{b}"} given)`

## Versions of i18n, rails, and anything else you think is necessary

Latest master (04a814b) of I18n
Ruby 2.5.3
No rails

----

Do note that this only occurs when a default with symbol is used. If the interpolation is in the primary key, everything works as expected.

```
I18n.backend.store_translations('en', a: '%{a}')
I18n.t('a', default: :a, key: '%{b}') # => "%{b}"
```

**Comment by radar** [comment]
To my knowledge, this is behaving correctly. You're specifying that the `key` should itself be interpolated, which means you have to pass a value for `b` as well:

```ruby
p I18n.t('missing', default: :a, key: '%{b}', b: "hello")
```

If it's exactly `"%{b}"` you want:

```ruby
p I18n.t('missing', default: :a, key: '%{b}', b: "%{b}")
```

**Comment by sliiser** [comment]
If they key is also supposed to be interpolated, then why is it not interpolated if the translation is not missing?
```ruby
I18n.backend.store_translations('en', a: '%{key}')
I18n.t('missing', default: :a, key: '%{b}') # => I18n::MissingInterpolationArgument
I18n.t('a', default: :a, key: '%{b}') # => "%{b}"
```

Also, with the solution you proposed, why is it interpolated exactly twice? Why not once and why not 3 times? Why is it expected that `I18n.t('missing', default: :a, key: '%{b}', b: '%{c}', c: '%{d}')` is exactly `"%{c}"` and not `"%{b}"` or `"%{d}"`

The "What I expected to happen" was what would be most convenient to me. I'm not saying  it's the only possible solution here, but what I'm after is consistency. Currently the default option is behaving differently than regular translation.
