### ISSUE TITLE
[ruby-2.7.0] warning: The last argument is used as the keyword parameter

### ISSUE THREAD

**Issue by alchimere** [ruby-i18n/i18n#500]
## What I tried to do

I tested one of my ruby project against ruby-2.7.0-preview3

## What I expected to happen

To work without warnings

## What actually happened

Warning because of ruby 2.7 keyword argument deprecations before ruby 3.0

## Versions of i18n, rails, and anything else you think is necessary

I18n 1.7.0 (standalone)

----

In a standard irb console with ruby-2.7.0-preview3

```ruby
2.7.0-preview3 :003 > I18n.translate('translate.key', { placeholder: 'value' })
(irb):3: warning: The last argument is used as the keyword parameter
/home/yberthou/.rvm/gems/ruby-2.7.0-preview3/gems/i18n-1.7.0/lib/i18n.rb:179: warning: for `translate' defined here
```

**Comment by radar** [comment]
Thank you for reporting this. Would you please be able to submit a PR that fixes this issue?

**Comment by alchimere** [comment]
@radar Yes I will soon

**Comment by alchimere** [comment]
I just realized nothing can be done in the method itself to fix this, so I added a comment that explain that.

So other developers will understand faster than me.
