### ISSUE TITLE
i18n 1.7.1 causes ActiveSupport to complain about `i18n` (require)

### ISSUE THREAD

**Issue by envygeeks** [ruby-i18n/i18n#506]
* What I tried to do: Upgrade from 1.7.0 t o 1.7.1
* What I expected to happen: No regressions, or errors.
* What actually happened
```
The i18n gem is not available. Please add it to your Gemfile and run bundle install
Error loading /Users/jordon/Development/<app>/.pryrc: cannot load such file -- i18n
```

## Versions of i18n, rails, and anything else you think is necessary

Works: v1.7.0
Bundler: v1.17.3, v2.x
Breaks: v1.7.1

----

This might be related to bundler in some way. _I say this because for some reason the gem claims to be installed via bundler... however it's nowhere to be seen in the actual `vendor/bundle` directory at all._

**Comment by radar** [comment]
Is i18n in your Gemfile?

**Comment by envygeeks** [comment]
@radar it is indeed.

```
# Frozen-String-Literal: true
# Encoding: utf-8

source 'https://rubygems.org'
ruby '~> 2.6'
gemspec

gem 'chewy'
gem 'faker'
gem 'pathutil'
gem 'rubocop'
gem 'redis'

gem 'i18n', '= 1.7.1'
```

The above doesn't work, however, switching it to `1.7.0` makes it work again.

**Comment by radar** [comment]
I tried reproducing this issue with a cut-down `Gemfile`:

```ruby
source 'https://rubygems.org'

gem 'i18n', '1.7.1'
```

But I am unable to.

I suspect it's something to do with how your machine is setup.

**Comment by knapo** [comment]
@envygeeks What do you have in `/Users/jordon/Development/<app>/.pryrc` ? probably it's causing the issue.
