### ISSUE TITLE
deep_merge! uses missing method

### ISSUE THREAD

**Issue by flash-gordon** [ruby-i18n/i18n#507]
## What I tried to do

Nothing, literally.

## What I expected to happen

I receive no CI report.

## What actually happened

i18n 1.8.0 was released and a scheduled build in dry-schema failed: https://github.com/dry-rb/dry-schema/runs/380987242
Backtraces lead to i18n where it calls `deep_merge` which is not defined.

## Versions of i18n, rails, and anything else you think is necessary

i18n 1.8.0

----

Here's a piece of code containing the bug: https://github.com/ruby-i18n/i18n/blob/d14906da0cbd658de334fcb43e9a750dab4ca387/lib/i18n/core_ext/hash.rb#L21-L33 The refinement doesn't include `deep_merge` so this code fails at line 26 in an environment missing activesupport extensions.

I'm sorry I didn't provide a repro as I don't have enough time atm but I hope this is enough.

**Comment by radar** [comment]
Reverted with #508. Pushed out with i18n 1.8.1 just now.

@CrAsH1101: would you happen to know why this has happened?

**Comment by radar** [comment]
Oh, looking at the code it looks like you will need to copy over the `deep_merge` method too. Please submit a PR for that if you wish to resurrect your other PR.

**Comment by vipera** [comment]
@radar I'll open the PR as this is my fault.

**Comment by CrAsH1101** [comment]
Test suit includes active_support so this "bug" is only possible in projects which do not require active_support. Maybe active_support should not be included in tests?

**Comment by flash-gordon** [comment]
Thanks folks! ❤️
