### ISSUE TITLE
Check your rails app?

### ISSUE THREAD

**Issue by OnlineGameGuy** [ruby-i18n/i18n#511]
For us first-time rails installers, would you mind being more specific than saying "check your rails app" in your overview?

Where is config/application.rb and do we need to add "config.i18n.fallbacks = [I18n.default_locale]" before installing rails for the time? If so, how?

Thanks.

**Comment by radar** [comment]
This post install message is only there for people upgrading older Rails applications. You can safely ignore that message.

**Comment by radar** [comment]
To be slightly clearer: older Rails apps used to have a line:

```
config.i18n.fallbacks = true
```

But this is not compatible with modern I18n, as that configuration takes an array instead.

**Comment by radar** [comment]
Perhaps 4e033dc will help.

**Comment by OnlineGameGuy** [comment]
Very much appreciated and I'm very pleased to say after THREE DAYS... I have my first Ruby on Rails server up and running using WSL.  w00t!
