### ISSUE TITLE
[BUG] Wrong fallback order of locales

### ISSUE THREAD

**Issue by syakovyn** [ruby-i18n/i18n#517]
## What I tried to do

Took an example from i18n/locale/fallbacks.rb:

> \#   \# using the default locale as default fallback locale
> \#
> \#   I18n.default_locale = :"en-US"
> \#   I18n.fallbacks = I18n::Locale::Fallbacks.new(:"de-AT" => :"de-DE")
> \#   I18n.fallbacks[:"de-AT"] # => [:"de-AT", :"de-DE", :de, :"en-US", :en]
> 

```ruby
require 'i18n'

I18n.available_locales = [:"de-AT", :"de-DE", :de, :"en-US", :en]
I18n::Backend::Simple.include(I18n::Backend::Fallbacks)

I18n.default_locale = :"en-US"
I18n.fallbacks = I18n::Locale::Fallbacks.new(:"de-AT" => :"de-DE")
pp I18n.fallbacks[:"de-AT"] # => [:"de-AT", :"de-DE", :de, :"en-US", :en]

```
## What I expected to happen

The output to match the example _[:"de-AT", :"de-DE", :de, :"en-US", :en]_

## What actually happened

The output was _[:"de-AT", :de, :"de-DE"]_

## Versions of i18n, rails, and anything else you think is necessary

i18n v1.8.2

Actually I don't care about the tail part  _:"en-US", :en_ but the order of the head _:"de-AT", :de, :"de-DE"_ is definitely wrong.

**Comment by radar** [comment]
This logic is actually correct. The example was wrong and was updated in https://github.com/ruby-i18n/i18n/commit/dfd1e29dddeea88a3015b8b1c7ce2b40991a2af8.  

The fallback is to `de` by default because `de` is considered a fallback local to `de-AT` first, before `de-DE` is considered.
