### ISSUE TITLE
Future Ideas & Deprecations

### ISSUE THREAD

**Issue by sandstrom** [ruby-i18n/i18n#522]
Are there any plans for upcoming functionality or deprecations for this gem?

Some ideas:

- Support for the ICU message format. There are [other implementations](https://github.com/format-message/message-format-rb) that we could use as dependencies or [collaborate with](https://github.com/twitter/twitter-cldr-rb).
- Drop support for legacy stuff
- Extract rarely used stuff into separate gems, for example support for po-files and/or gettext.

cc @radar

**Comment by radar** [comment]
There are no current plans for upcoming functionality for this gem. I would consider it to be "complete" and in maintenance mode. That is to say, I will accept PRs to fix bugs and security issues. PRs for features probably not so much.

There no plans to deprecate rarely used stuff into separate gems either.
