### ISSUE TITLE
[BUG] Add changelog to v1.8.5

### ISSUE THREAD

**Issue by ShockwaveNN** [ruby-i18n/i18n#538]
There is no changelog for this version

![Screenshot from 2020-07-24 10-25-50](https://user-images.githubusercontent.com/668524/88369976-d6767800-cd99-11ea-86f2-da10b472fe7a.png)

**Comment by radar** [comment]
https://github.com/ruby-i18n/i18n/releases/tag/v1.8.5 Done.

**Comment by ShockwaveNN** [comment]
@radar Thanks
