### ISSUE TITLE
I18n.load_path Error (Translations not found)

### ISSUE THREAD

**Issue by luke-hill** [ruby-i18n/i18n#540]
## What I tried to do

When using ActiveSupport as an "unactivated" gem. It adds lines to your default load path. This then seems to not like working with the `<<` operator and scanning all load_path directories for language files.

## What I expected to happen

The `I18n.load_path` array to be scanned legitimately for any and all signs of a key

## What actually happened

`I18n.load_path` did not scan all available paths.

## Versions of i18n, rails, and anything else you think is necessary
**I18n - 1.8.5**
**Cucumber v3/v4**

**Cucumber 3**
```
I18n.load_path => [["/home/{your_project}/config/locales/en.yml", "/home/{your_project}/config/locales/cy.yml"]]
```

**Cucumber 4** - This auto-appends extras from AS
```
I18n.load_path => ["/home/luke/.rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.4/lib/active_support/locale/en.yml", "/home/luke/.rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.4/lib/active_support/locale/en.rb", [["/home/{your_project}/config/locales/en.yml", "/home/{your_project}/config/locales/cy.yml"]]
```

When using the bottom config (Which has 3 yml files and 1 rb file. A translation key (That exists), is not loaded.

**Cucumber 3**
```
# en.yml
en:
  change_language: Cymraeg

# Some ruby file
I18n.t(:change_language) => "Cymraeg"
```

**Cucumber 4**
```
# en.yml
en:
  change_language: Cymraeg

# Some ruby file
I18n.t(:change_language) => "translation missing: en.change_language"
```

**Comment by luke-hill** [comment]
Any thoughts from anyone here if they can reproduce or suchlike? @radar or someone else?

**Comment by radar** [comment]
It might help me to have a Ruby project that I can clone to try this out.

**Comment by luke-hill** [comment]
Urm oki. Let me have a think how to put together a really small one. Because I "think" the moving parts are quite small.

I'll create a brand new project on GH in the next day or so and link it to you

**Comment by luke-hill** [comment]
In attempting to re-create this and show-case the error from cucumber 3->4 I was unable to do so.

Further investigation found that this was limited to a patch version in cucumber. And the latest revision of cucumber4 doesn't feature this.

Given it's isolated to one specific version of a gem that only implicitly consumes i18n. I'm just going to close it off. Sorry for the hassle!

**Comment by radar** [comment]
@luke-hill Thank you for spending some time investigating this and digging a little deeper. Good to know that it's limited to a _specific_ release of Cucumber. I appreciate your effort.
