### ISSUE TITLE
Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

### ISSUE THREAD

**Issue by ruksina25** [ruby-i18n/i18n#561]
Thanks for opening this issue. A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

__Originally posted by @welcome in https://github.com/github/docs/issues/3914#issuecomment-783970496__

**Comment by radar** [comment]
@ruksina25: could you please test this issue feature out on your own repository, rather than i18n? I keep getting email notifications here for your issues.
