### ISSUE TITLE
Typo: Function store_translations() misses closing parenthesis

### ISSUE THREAD

**Issue by pink-ink** [ruby-i18n/i18n#575]
In file i18n.rb, from line 263:
Function store_translations() in comment of transliterate function misses a closing parenthesis.
If I copy/paste the example of how to make a proc to my code, it's not working.
It's 3 opening but only 2 closing parenthesis. This should be corrected.

**Comment by patrickgramatowski** [comment]
@radar May we close this issue now? 👍

**Comment by pink-ink** [comment]
Thank you very much for the fix and for closing the issue
