### ISSUE TITLE
Interpolation of numeric values to Arabic translation

### ISSUE THREAD

**Issue by adi-ronen** [ruby-i18n/i18n#605]
Hello 😃 

I have a translation key that build like that:
```ruby
key: 'translation_key'
value: 'translation %{value}'
```
The value is two numbers separated by a dash, for example "1-10"

 ```ruby
i18n.t 'translation_key', value: "1-10"
```
The results:
LTR
```ruby
English: translation 1-10
```
RTL
```ruby
Hebrew: 1-10 תרגום
Arabic: 10-1 ترجمة
```
In Arabic the numbers are flipped.

I tested multiple characters between the two numbers and adding a dot or a comma between numbers does not change their order (thanks god 😜 ).

Greater than (>) is flipping the numbers both in Hebrew and in Arabic. 

I expect that RTL languages will have the same behaviour. 1-10 and 10-1 have a different meaning.
Is this something you can fix or is there some flag i can use so this interpolation wont flip my numbers?

## Versions
i18n - 1.8.9
rails - 6.0.3.6

Thanks! :heart:

**Comment by radar** [comment]
> Greater than (>) is flipping the numbers both in Hebrew and in Arabic.

Where is this greater than?

**Comment by radar** [comment]
Could you please provide an application that reproduce this issue? That would help me immensely.

**Comment by adi-ronen** [comment]
@radar [here](https://github.com/adi-ronen/translation-test) is an application that reproduce this issue.

**Comment by radar** [comment]
Thank you @adi-ronen. I think this has to do with how browsers interpret Arabic characters. You are likely running into this issue: https://stackoverflow.com/questions/8227183/rtl-is-on-web-page-reverses-numbers-with-a-dash
