### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lluchez** [ruby-i18n/i18n#609]
## What I tried to do

CI Deploy

## What I expected to happen

I'm able to bundle my application using the latest version of i18n (`1.9.0`)

## What actually happened

```
Your bundle is locked to i18n (1.9.0), but that version could not be found in
any of the sources listed in your Gemfile. If you haven't changed sources, that
means the author of i18n (1.9.0) has removed it. You'll need to update your
bundle to a version other than i18n (1.9.0) that hasn't been removed in order to
install.
```

`Gemfile.lock`:
```
    i18n (1.9.0)
      concurrent-ruby (~> 1.0)
```

RubyGem website (listed version is `1.9.1`), instead of `1.9.0`:
![image](https://user-images.githubusercontent.com/24396004/151448484-dfae9aad-d01b-4643-a9de-55a10fbdd43b.png)

Thanks! :heart:

**Comment by codealchemy** [comment]
`1.9.0` was yanked (ref: https://github.com/ruby-i18n/i18n/pull/602)
![Screen Shot 2022-01-27 at 13 49 46](https://user-images.githubusercontent.com/4504083/151449460-8593ed8f-38c3-46f6-8f9d-606f26ba25f0.png)

**Comment by lluchez** [comment]
Thanks for the quick reply!

**Comment by radar** [comment]
Yeah, i18n 1.9.0 was broken in a bad way, so it's better if it is not installable.
