### ISSUE TITLE
Release 1.9.0 disappeared from rubygems.org

### ISSUE THREAD

**Issue by pil0u** [ruby-i18n/i18n#610]
https://rubygems.org/gems/i18n/versions

It broke my build on Heroku, I updated to 1.9.1 to be fine. Is this deletion intended?

**Comment by tachyons** [comment]
Yes, 1.9.0 is yanked. See discussion [here](https://github.com/ruby-i18n/i18n/pull/602#issuecomment-1023629568)

**Comment by pil0u** [comment]
Thanks for the link, I hit a bad timing :-)
