### ISSUE TITLE
[QUESTION] Does i18n use Semver?

### ISSUE THREAD

**Issue by ebouchut** [ruby-i18n/i18n#632]
I may be wrong but it seems to me that `i18n` does not [support Semantic Versioning](https://semver.org) as version [1.11.0](https://github.com/ruby-i18n/i18n/releases/tag/v1.11.0) (a minor version) introduced what looks to me as [a breaking change](https://github.com/ruby-i18n/i18n/pull/630#issuecomment-1182666844) where the `zero` (and `one` when `count` is not present) keys are no longer supported.

Clarifying this point in the README would help given the impact it may have on 3rd party gems.

Thanks,

**Comment by radar** [comment]
Yes it does.

the change appeared to me to be just for CLDR. If it’s breaking other things, then please do file an issue about that breakage (following the issue guide) so that we can fix it.

Thanks!

**Comment by radar** [comment]
I’ve just started my day (read: I’m still in bed) and read the other thread. Once I’m at work today, I’ll look at how we can fix this proper.
