### ISSUE TITLE
[BUG] `%P` gets stripped from `localize` formats for `Date` objects

### ISSUE THREAD

**Issue by movermeyer** [ruby-i18n/i18n#639]
## What I tried to do

```ruby
(byebug) date = Date.new(2018, 12, 26)
Wed, 26 Dec 2018
(byebug) date.to_datetime.iso8601
"2018-12-26T00:00:00+00:00"
(byebug) I18n.locale = :en
:en
(byebug) I18n.l(date, format: :friendly_date_time)
```

```yaml
en:
  date:
    formats:
      friendly_date_time: "%b %-d, %Y, %-l:%M %P"
```

## What I expected to happen

```
"Dec 26, 2018, 12:00 am"
```

## What actually happened

```
"Dec 26, 2018, 12:00 "
```

The resulting datetime is 12 hours off, since without the Meridian indicator (i.e., `am/pm`), it can only be reasonably interpreted as a 24-hour clock datetime.

## Versions of i18n, rails, and anything else you think is necessary

* `i18n`: `v1.12.0`
* Ruby: `ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]`

## Explanation

`I18::Backend::Base#translate_localization_format` [strips `%p/%P`](https://github.com/ruby-i18n/i18n/blob/c5ccd28f8413f44baf6e32aeeb80854471650533/lib/i18n/backend/base.rb#L285-L286) unless `object.respond_to?(:hour)`. `Date#hour` is a private method, so `object.respond_to?(:hour)` is `false`, despite `Date#strftime` supporting the `%p/%P` fields:

```ruby
date.strftime("%b %-d, %Y, %-l:%M %P")
"Dec 26, 2018, 12:00 am"
```

This conditional was added in [this commit](https://github.com/ruby-i18n/i18n/commit/24dc870825228a612688f69f38fa9f6c8854c606) (2008-06-17).

**Comment by radar** [comment]
What an obscure catch this is :) 

Thank you very much for taking the time to investigate the issue and submit a fix as well.
