### ISSUE TITLE
Norwegian Locale YAML File (no.yml) Causes Error

### ISSUE THREAD

**Issue by partydrone** [ruby-i18n/i18n#64]
Placing a Norwegian YAML file (no.yml) anywhere in the 'config/locales' directory throws the following error whenever the `t()` method is called:

```
undefined method `to_sym' for false:FalseClass
```

Here is a sample line of code that throws the error:

```
<p id="ticker-headline"><%= link_to t('views.home.headlines'), news_path %></p>
```

Changing the locale file to a Ruby file (no.rb) and reformatting as a hash works around this issue.

**Comment by silambarasanmkce** [comment]
@knapo but the browser is sending the text for norweign as `no` how can i map the text with norweign language

**Comment by knapo** [comment]
@silambarasanmkce Just implement the mapping in the place, where you set local from param or session.
