### ISSUE TITLE
 cannot load such file -- i18n/core_ext/hash (LoadError)

### ISSUE THREAD

**Issue by aliahmadexe** [ruby-i18n/i18n#641]
## What I tried to do

* Upgraded from Rails 5 to Rails 6. 
* previous version of i18n was 0.9.5
* upgraded version is 1.12.0 due to active support version is 6.1.4.1

## What I expected to happen

* to Work smoothly

## What actually happened

* Gems installed successfully but when i run the console i got Error
.rvm/gems/ruby-2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require': cannot load such file -- i18n/core_ext/hash (LoadError) 
## Versions of i18n, rails, and anything else you think is necessary
i18n = 1.12.0
Rails = 6.1.4.1
Ruby = 2.7

**Comment by scottbearden** [comment]
I get the same error from gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in
**Versions of i18n, rails, and anything else you think is necessary**
i18n = 1.12.0
Rails = 6.0.5.1
Ruby = 3.0.2

**Comment by aliahmadexe** [comment]
i got it with chewy gem. 
Because it was explicitly calling i18n hash. 
so i monkey patch its old version because i am working on a 12 years old Repo.
following is the link of my PR. i just replace a single line in chewy.rb. 
https://github.com/aliahmadexe/chewy/tree/i18n

**Comment by radar** [comment]
Please provide an app that reproduces this issue.

Ryan
