### ISSUE TITLE
[BUG] config.i18n.fallbacks not respected on Rails 7

### ISSUE THREAD

**Issue by yheuhtozr** [ruby-i18n/i18n#645]
## What I tried to do

``` ruby
class Application < Rails::Application
  config.load_defaults 7.0
  config.i18n.fallbacks = { "en-AU": %i[en-GB en-US en] }
end
```

## What I expected to happen

``` bash
$ rails c
Loading development environment (Rails 7.0.4)          
irb(main):001:0> I18n.fallbacks
=> {:"en-AU"=>[:"en-GB", :"en-US", :en]}
```

## What actually happened

``` bash
$ rails c
Loading development environment (Rails 7.0.4)          
irb(main):001:0> I18n.fallbacks
=> {:en=>[:en]}
```

## Versions of i18n, rails, and anything else you think is necessary

- Ruby: 3.0.2
- Rails: 7.0.4
- i18n: 1.12.0
- OS: Ubuntu 21.04 (WSL2)

## Workaround

https://github.com/ruby-i18n/i18n/blob/fbc9b2b502ec373519d45a7b6da4ddc9243404c4/lib/i18n/locale/fallbacks.rb#L67-L80

It seems to work ~~as expected~~[^1] if you add one line between the line 76-77 as follows:

``` ruby
        if args.count == 1 && !block_given?
          mappings = args.first
          mappings.each do |from, to|
            from, to = from.to_sym, Array(to)
            to.each do |_to|
              @map[from] ||= []
              @map[from] << _to.to_sym
            end
          end
          self.replace(@map) # <- insert this!
        else
          @map.map(*args, &block)
        end
```

[^1]: not exactly, it'll be like `{:"en-AU"=>[:"en-GB", :"en-US", :en], :en=>[:en]}`

**Comment by radar** [comment]
Notably, this happens in Rails 6.1 as well.
