### ISSUE TITLE
[BUG] Possible Denial of Service

### ISSUE THREAD

**Issue by Akashkarmakar787** [ruby-i18n/i18n#667]
## What I tried to do

* Slow regex is being used:
https://github.com/ruby-i18n/i18n/blob/master/lib/i18n/backend/interpolation_compiler.rb#L24-L25

        TOKENIZER                    = /(%%\{[^\}]+\}|%\{[^\}]+\})/
        INTERPOLATION_SYNTAX_PATTERN = /(%)?(%\{([^\}]+)\})/
## What I expected to happen

* solve the statement without taking much time.

## What actually happened

* Possible ReDoS. Can even crash the system in worst case
* https://medium.com/@akashkarmakar787/redos-the-killer-stuff-7a28b14d80e

## Versions of i18n, rails, and anything else you think is necessary

* <=1.4.1.    i18n affected.

----

Bonus points for providing an application or a small code example which reproduces the issue.

<img width="811" alt="Screenshot 2023-06-08 at 11 34 32 AM" src="https://github.com/ruby-i18n/i18n/assets/26542342/64c2487b-7cea-4384-9d0f-fbb7e428f53f">
Thanks! :heart:

**Comment by radar** [comment]
Believe these will be fixed by #668 and #669

**Comment by Akash-Karmakar-e3082** [comment]
@radar Can we have a CVE for the issue?

**Comment by kbrock** [comment]
@Akash-Karmakar-e3082 you passed in a 40k character string, and it was going through character by character.

It had 4 checks per character, so it was 40k * 3 checks.
It did not have any major backtraces, so it did not exhibit the `O(n^2)` slowdown like you had in your referenced article.

If you have reason to believe that this with exponentially take longer, please share how you came to that conclusion.

Also, can you share a quick example of why someone would localize content that was entered by a user? (An admin does not count. if the admin is nefarious, then they may as well just format the disk and be done)
