### ISSUE TITLE
[BUG] Unnecessary Ruby < 3.2 warning 

### ISSUE THREAD

**Issue by qbantek** [ruby-i18n/i18n#704]
## What I tried to do

Run bundle install on ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23] and a Gemfile containing `i18n 1.14.6`

## What I expected to happen

No warnings.

## What actually happened

Got the following warning asking to upgrade to Ruby > 3.2 (I am on 3.3.4)

```
Post-install message from i18n:
PSA: I18n will be dropping support for Ruby < 3.2 in the next major release (April 2025), due to Ruby's end of life for 3.1 and below (https://endoflife.date/ruby). Please upgrade to Ruby 3.2 or newer by April 2025 to continue using future versions of this gem.
```

## Versions of i18n, rails, and anything else you think is necessary

ruby 3.3.4 (2024-07-09 revision be1089c8ec) 
i18n 1.14.6

----

Bonus points for providing an application or a small code example which reproduces the issue.

Thanks! :heart:

**Comment by radar** [comment]
Same issue as #702. I'll fix it up next week. Thanks for reporting.
