### ISSUE TITLE
interpolate.rb % override on String insufficient for usage as seen in test-unit

### ISSUE THREAD

**Issue by jacobo** [ruby-i18n/i18n#9]
test-unit (http://test-unit.rubyforge.org/svn/trunk/lib/test/unit/ui/console/testrunner.rb) line 116 does this:
output("%g%% passed" % pass_percentage, result_color)

and gets the exception:  one hash required (ArgumentError)

reproduce in irb:

> > puts("%g%% passed" % 100, "\e[36m")
> > 100% passed

then:

> > require 'i18n'
> > puts("%g%% passed" % 100, "\e[36m")
> > ArgumentError: one hash required

my ruby --version is
ruby 1.8.7 (2008-08-11 patchlevel 72) [universal-darwin10.0]

**Comment by harryhandsome** [comment]
hlo
